### ISSUE TITLE
User signout  is not working.

### ISSUE THREAD

**Issue by ricardodovalle** [castlewhitehall/meanjs-with-token-auth#1]
Hi @acoulon99 , 

I tried to use your project to learn how to use token authentication with MEAN.js, but user signout is not working. I think, it is because missing the post from angular view, but I am learning Angular and Node.js and I don't how to fix it yet.

Thank you very much. :+1:

**Comment by ricardodovalle** [comment]
@acoulon99  I am trying to use token authentication with version 0.4.0 of MEAN.js. I used your code with jsonwebtoken instead jwt-simple. https://github.com/ricardodovalle/meanjs-token-auth

I will appreciate any help or suggestion, I am a Node.js beginner. 
Thanks.

**Comment by acoulon99** [comment]
Hey, 

Sorry for the delay. I was pretty busy with a couple of things.

You are correct, user signout isn't working yet, and there are a number of loose ends that need to be tied. We're needing this internally as well, so this is perfect timing. I'll be working on this again starting today and into next week.

**Comment by acoulon99** [comment]
I'll also be updating the documentation which should help you apply this to your own deployment of the MEANjs stack.

**Comment by ricardodovalle** [comment]
Hi @acoulon99, thank you very much :+1: 
I create a thread inside mean.js github project too.

**Comment by acoulon99** [comment]
Ok, I updated the project a bit.

Signout should work now, but not from the Angular web app yet. I added a couple of test cases to the test folder which should demonstrate how the end point works. I'm also going to work on a set of instructions for building and deployment as well as highlight the key changes I've made while including tokens.

It's still a young project, but hopefully with community help we can make a solid tool that others can reference. Some next steps include removing/refactoring most of the Angular app so that it's simpler to learn from.
